#!groovy

pipeline {
    agent any
    environment {
        aws_credential = 'AWS_CREDENTIALS'
        region = 'sa-east-1'
        dist_folder = 'dist/plataforma-teologia'
        aws_bucket = 'plataforma-teologia-frontend'
    }
    tools { nodejs 'node' }
    stages {
        stage('Checkout') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage('Dependencies download') {
            steps {
                sh 'npm install'
                sh 'npm install -g @angular/cli'
            }
        }

        stage('Build application') {
            steps {
                sh 'ng build --configuration=production'
            }
        }

        stage('Deploy') {
            steps {
                withAWS(region:"${region}", credentials:"${aws_credential}") {
                    s3Upload(bucket:"${aws_bucket}", path:"", workingDir:"${dist_folder}", includePathPattern:'**/*')
                }
        }
    }
}
}
